spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelogs/db.changelog-master.yaml